name = "DragonRealm Unofficial"
author = "ReikaKaleski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa0fa83c6e5732ae01c96012a66d18c8abfaed00e6e50cf79764a9cde4243f10"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
unsup = "1.2.0"
